name: MLOS Autotuning DevContainer

on:
  workflow_dispatch:
    inputs:
      tags:
        description: Manual MLOS Autotuning DevContainer run aux info tags
      NO_CACHE:
        type: boolean
        description: Disable caching?
        default: false
        required: false
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    types: [checks_requested]
  schedule:
    - cron: "1 1 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  DevContainer:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_INLINE_CACHE: 1

    steps:
    - uses: actions/checkout@v4

    - name: Build devcontainer image
      run: |
        set -x
        pwd
        ls -la
        ./.devcontainer/build/build-devcontainer.sh

    - name: Create devcontainer
      run: |
        set -x
        pwd
        ls -la
        ./.devcontainer/scripts/create-devcontainer.sh

    - name: Run tests in devcontainer
      run: |
        echo "TODO"
        false
