name: MLOS Demo Markdown Link Check

on:
  workflow_dispatch:
    inputs:
      tags:
        description: Manual MLOS Demo Markdown Link Check run
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    types: [checks_requested]

jobs:
  # Check in-repo markdown links
  markdown-link-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: yes
        use-verbose-mode: yes
        folder-path: './config, ./.devcontainer'
        file-path: './README.md'
        config-file: './.github/workflows/markdown-link-check-config.json'
